### ISSUE TITLE
Thread Deadlocks HttpClient Awaiter

### ISSUE THREAD

**Issue by JoeDM09** [PawelGerr/Thinktecture.Abstractions#1]
I'm not sure the exact fail scenario however when I call a dependency from a WebService the awaiter for the HttpClient tasks such as PostAsync never return.

This issue can be solved when directly interacting with the native System.Net.HttpClient by calling .ConfigureAwait(false) however the awaiter cannot be configured for within Thinktecture HttpClientAdapter and therefore the native HttpClient which is being wrapped is never able to return a result and hangs forever.

**Comment by PawelGerr** [comment]
Good point! It is a common issue when using synchronization mechanisms (like `Thread.Wait()`, `Thread.Result` or `Task.GetAwaiter().GetResult()`) in environments having synchronization contexts without thread pools (like web service or WPF app).

Here is a good explanation about that https://msdn.microsoft.com/en-us/magazine/jj991977.aspx

Best practice for a lib would be to add `ConfigureAwait(false)` to all async methods but that is kind of a moral conflict because I want the lib to be free of custom logic as possible.
Better solution if I stop *awaiting* Tasks in my code so that the caller (i.e you) can decide whether to configure the awaiter to continue on captured context or not.

My current code of `GetAsync`
```
public async Task<IHttpResponseMessage> GetAsync(string requestUri)
{
	return (await _client.GetAsync(requestUri)).ToInterface();
}
```

After change
```
public Task<IHttpResponseMessage> GetAsync(string requestUri)
{
	return _client.GetAsync(requestUri)
		.ContinueWith(task => task.Result.ToInterface());
}
```

If you have time you can make a pull request :) otherwise I will do that in the near future.

**Comment by PawelGerr** [comment]
@JoeDM09 try out the new version 1.3.3

**Comment by JoeDM09** [comment]
@PawelGerr Awesome, I'll pull it in and give it a try but I'm pretty sure this will fix my particular issue. I vaguely understand how the deadlock scenario happens but didn't know how to give instructions to replicate.

**Comment by JoeDM09** [comment]
Just a quick update to confirm this works as expected. Plus now we can get the task without starting it immediately :)
