### ISSUE TITLE
.NET 4.7 support 

### ISSUE THREAD

**Issue by michaelmcdonoghGen3** [PawelGerr/Thinktecture.Abstractions#4]
When will .net 4.7 be supported.

**Comment by PawelGerr** [comment]
Are there some issues if you use .NET 4.5/4.6 or .NETStandard packages in a .NET 4.7 project?

**Comment by tavisbasing** [comment]
Hi, 

The issue we are experiencing with the [Thinktecture.Net.Http.Abstractions] package is that it relies on [System.Net.Http], but when we upgrade to .NET 4.6.2 [System.Net.Http] is now part of the framework and no longer requires it to be referenced, and because of this  [Thinktecture.Net.Http.Abstractions] is trying to re-reference [System.Net.Http] and causing invalid package referencing.

Is this something you are aware of, or do you have a solution around this issue?

**Comment by PawelGerr** [comment]
@tavisbasing thank you for the report.
Can I get the contents of your csproj, so I can reproduce the issue?

**Comment by PawelGerr** [comment]
@michaelmcdonoghGen3 @tavisbasing 
I can't reproduce the problem. Do you have a repro for me?

**Comment by PawelGerr** [comment]
The problem should be solved in version 2.2.0

**Comment by PawelGerr** [comment]
This could be the answer: https://twitter.com/terrajobst/status/997265096609972224
