### ISSUE TITLE
UnsafeConvert

### ISSUE THREAD

**Issue by orloffm** [PawelGerr/Thinktecture.Abstractions#6]
As a feedback: awesome work, but what is the purpose of having `UnsafeConvert` in the interface?

If I am implementing my own, say, `ITextWriter`, I have to implement this method twice, but it doesn't make any sense, what could I possibly return here? There may be _some_ class I'm wrapping, but it won't be a 100% match to `ITextWriter`, so why bother getting the wrapped item?

Plus, the default ReSharper's implementation doesn't always readily work, and the `[[EditorBrowsable(EditorBrowsableState.Never)]` feels hackish.

Why not:

1. Leave this method in `AbstractionAdapter<TImplementation>`.
2. Make it `internal`.
3. Implement the `ToImplementation` extensions on `IAbstraction<T> abstraction` as `(abstraction as Abstraction<T>)?.UnsafeConvert()`?

This way there won't be this garbage in custom implementations, and the method will be truly hidden.

Thanks.

**Comment by PawelGerr** [comment]
Thank you for the feedback but the proposal doesn't work with inherited types.

Let's take the `IStream`/`StreamAdapter` as an example

```
public class StreamAdapter : AbstractionAdapter<Stream>, IStream
{
}
```

Having an instance of `IStream` we can easy cast it to `AbstractionAdapter<Stream>` and call `UnsafeConvert()`.

Let's see at inherited type `IBufferedStream`/`BufferedStreamAdapter`

```
public class BufferedStreamAdapter : StreamAdapter, IBufferedStream
{
}
```

An instance of `IBufferedStream` cannot be casted to `AbstractionAdapter<BufferedStream>` because `BufferedStreamAdapter` doesn't derives from  `AbstractionAdapter<BufferedStream>` but from `StreamAdapter` and there is no multiple inheritance in .NET.

To make it possible we have to derive from `AbstractionAdapter<BufferedStream>` und implement all members of `IStream` anew although they are implemented in `StreamAdapter` already.

```
public class BufferedStreamAdapter : AbstractionAdapter<BufferedStream>, IBufferedStream
{
	// all member of IStream have to be implemented yet again (or rather copied from StreamAdapter)
}
```

And if you want to remove `UnsafeConvert` from IntelliSense then we have to implement the interface `IAbstraction<T>` explicitly.
That means, instead of

```
public new BufferedStream UnsafeConvert()
{
	return Implementation;
}
```
we use

```
BufferedStream IAbstraction<BufferedStream>.UnsafeConvert()
{
	return Implementation;
}
```

That should be enough.


If I am missing something then feel free to fork the repo and try some new ideas. I am thankful for any help.

Until then I will wait for the following proposal that opens up new ways for writing this kind of abstractions: https://github.com/dotnet/csharplang/blob/master/proposals/default-interface-methods.md
